/** Generated, vendored or machine-owned: not ours to format. */
export const prettierIgnoreFile = `.svelte-kit
build
db

# generated
src/lib/paraglide
src/lib/ROUTES.ts
project.inlang
messages
pnpm-lock.yaml
package-lock.json

# vendored agent tooling
.agents
.claude
.cursor
.github
skills
skills-lock.json
`

/** kitql's shared eslint + prettier setup, same as firstly and kimbia. */
export const eslintConfigFile = `import { kitql } from '@kitql/eslint-config'

/** @type { import('eslint').Linter.Config[]} */
export default [
  // Generated by paraglide, not ours to lint.
  { ignores: ['src/lib/paraglide/**', 'src/lib/ROUTES.ts'] },
  ...kitql(),
]
`

export const prettierConfigFile = `import { kitql } from '@kitql/eslint-config/.prettierrc.js'

export default {
  ...kitql(),
}
`

/**
 * adapter-node ships no compression, and a compressed SSE stream never flushes -
 * so liveQuery would silently stop updating. Hence: compress everything but the stream.
 */
export const prodServerFile = `import compression from '@polka/compression'
import polka from 'polka'

import { handler } from '../build/handler.js'

const compress = compression({ threshold: 1024 })

polka()
  .use((req, res, next) => {
    // remult's SSE endpoint: buffering it would freeze every liveQuery.
    if (req.url.startsWith('/api/stream')) return next()
    compress(req, res, next)
  })
  .use(handler)
  .listen(Number(process.env.PORT ?? 3000), () => {
    console.info(\`listening on \${process.env.PORT ?? 3000}\`)
  })
`
