import type { Ctx } from '../ctx.ts'
import { lines } from '../lines.ts'

export function readme(ctx: Ctx, name: string) {
  return lines(
    `# ${name}`,
    ``,
    `SvelteKit + [remult](https://remult.dev)${ctx.ff ? ' + [firstly](https://firstly.fun)' : ''}, scaffolded with \`sv add @remult\`.`,
    ``,
    '```sh',
    `npm install`,
    `npm run dev`,
    '```',
    ``,
    `## What is where`,
    ``,
    `| Path | What |`,
    `| --- | --- |`,
    `| \`src/routes/(public)/\` | public landing + sign-in |`,
    `| \`src/routes/app/\` | the app itself${ctx.auth ? ' (sign-in required)' : ''} |`,
    ctx.internal && `| \`src/routes/app/internal/\` | backstage: users, crons, mails, SQL console |`,
    `| \`src/modules/<feature>/\` | one folder per feature: entity, \`.server.ts\`, \`.remote.ts\`, UI |`,
    `| \`src/lib/server/api.ts\` | the backend, in one file |`,
    `| \`src/lib/site.ts\` | app name, tagline, OG description |`,
    ctx.auth && `| \`src/modules/auth/\` | User, session, guard, login-as (\`?login-as=email\`) |`,
    `| \`src/lib/\` | shared across features: roles, site identity, ui primitives |`,
    `| \`messages/*.json\` | translations (paraglide) |`,
    ``,
    `## The loop`,
    ``,
    `1. Add a field to an entity.`,
    `2. Refresh.`,
    ``,
    `The REST API, the TypeScript types${ctx.admin ? ', the Admin UI' : ''} and the validation follow. There is no`,
    `API layer to write.`,
    ``,
    `## Database`,
    ``,
    `JSON files in \`./db\` out of the box - nothing to install. Want postgres?`,
    ``,
    '```sh',
    `docker compose up -d`,
    `echo 'DATABASE_URL="postgres://postgres:postgres@localhost:5432/app"' >> .env`,
    '```',
    ``,
    `Restart, and remult creates the schema. Nothing else changes.`,
    ``,
    ctx.auth && `## Who is admin`,
    ctx.auth && ``,
    ctx.auth && `**The first account created owns the app.** Open \`/login\`, type your email, and you hold`,
    ctx.auth && `every role - no seed data, no database edit, same in dev and in production.`,
    ctx.auth && ``,
    ctx.auth && `Everyone after that is a plain member. Add teammates from \`/app/internal/users\` (or let`,
    ctx.auth && `them sign in themselves), then use the avatar menu to see the app as them.`,
    ctx.auth && ``,
    ctx.auth && `Locked out? \`SUPER_ADMIN_EMAILS\` is the escape hatch: any email listed there holds every`,
    ctx.auth && `role, whatever the database says. \`REQUIRE_EMAIL_VERIFICATION=true\` adds a mailed link`,
    ctx.auth && `before a first sign-in.`,
    ctx.auth && ``,
    `## Deploy`,
    ``,
    `Built with \`@sveltejs/adapter-node\`, served by \`scripts/prod-server.js\` (gzip everywhere except`,
    `remult's SSE endpoint - compressing it would freeze live queries).`,
    ``,
    '```sh',
    `npm run build`,
    `npm start        # PORT defaults to 3000`,
    '```',
    ``,
    `Set in your host: \`DATABASE_URL\`${ctx.auth ? ' and `AUTH_SECRET`' : ''}.`,
    ``,
    `**Railway / Render / Fly / any Docker host**: build command \`npm run build\`, start command`,
    `\`npm start\`, add a postgres and paste its connection string into \`DATABASE_URL\`. remult creates`,
    `the tables on boot - no migration step in the pipeline.`,
    ``,
    `**Vercel / Netlify / Cloudflare**: swap the adapter (\`npx sv add sveltekit-adapter\`) and drop`,
    `\`scripts/prod-server.js\`; those platforms compress for you. Note that a serverless host kills`,
    `long-lived SSE connections, so live queries fall back to polling.`,
    ``,
    `## Agents`,
    ``,
    `\`AGENTS.md\` holds this project's rules. The library patterns come from skills installed`,
    `from the source repos - \`npm run skills\` to install, \`npm run skills:update\` to refresh.`,
    `Nothing to copy, nothing to keep in sync.`,
    ``,
    `## Docs`,
    ``,
    `- remult: https://remult.dev/docs`,
    ctx.ff && `- firstly: https://firstly.fun`,
    `- sveltekit: https://svelte.dev/docs/kit`,
    ``,
  )
}
