<script lang="ts">
  import { remult } from "remult";
  import Tile, { type TileStatus } from "./Tile.svelte";

  let status = $state<TileStatus>("Loading");

  $effect(() => {    
    fetch(`${remult.apiClient.url}/admin/__entities-metadata`)
      .then((response) => {        
        if (response.ok)   status = "Success";
        else status = "Error";
      })
      .catch(() => status = "Error");
  });

  let subtitle = $derived(
    status === "Error" ? "There seems to be an issue" : ""
  );
  let message = $derived(
    status === "Success"
      ? "Remult Admin is an autogenerated UI for managing your data."
      : "Is admin enabled in remultApi config?"
  );
  let canOpenAdmin = $derived(status === "Success");
</script>

<Tile title="Admin" {status} {subtitle} width="half">
  <p>{message}</p>
  <div class="button-row">
    {#if canOpenAdmin}
      <a class="button" href={`${remult.apiClient.url}/admin`}> Open Admin </a>
    {/if}
  </div>
</Tile>
