<script lang="ts">
  import { onMount } from "svelte";
  import Tile, { type TileStatus } from "./Tile.svelte";

  let status: TileStatus = "Loading";
  let canOpenAdmin = false;

  onMount(() => {
    fetch("/api/admin")
      .then((response) => {
        if (response.ok) {
          status = "Success";
          canOpenAdmin = true;
        } else {
          status = "Error";
          canOpenAdmin = false;
        }
      })
      .catch(() => {
        status = "Error";
        canOpenAdmin = false;
      });
  });

  $: subtitle = status === "Error" ? "There seems to be an issue" : "";
  $: message =
    status === "Success"
      ? "Remult Admin is an autogenerated UI for managing your data."
      : "Failed to connect to Remult server.";
</script>

<Tile title="Admin" {status} {subtitle} width="half">
  <p>{message}</p>
  <div class="button-row">
    {#if canOpenAdmin}
      <a class="button" href="/api/admin"> Open Admin </a>
    {/if}
  </div>
</Tile>
