import { remult } from "remult";
import { Component, OnInit } from "@angular/core";
import { TileComponent, type TileStatus } from "../tile/tile.component";

@Component({
  selector: "app-admin",
  templateUrl: "./admin.component.html",
  styles: [":host { display: contents; }"],
  standalone: true,
  imports: [TileComponent],
})
export class AdminComponent implements OnInit {
  status: TileStatus = "Loading";
  canOpenAdmin: boolean = false;

  get subtitle(): string {
    return this.status === "Error" ? "There seems to be an issue" : "";
  }

  get message(): string {
    return this.status === "Success"
      ? "Remult Admin is an autogenerated UI for managing your data."
      : "Is admin enabled in remultApi config?";
  }

  ngOnInit(): void {
    fetch(`${remult.apiClient.url}/admin/__entities-metadata`)
      .then((response) => {
        if (response.ok) {
          this.status = "Success";
          this.canOpenAdmin = true;
        } else {
          this.status = "Error";
          this.canOpenAdmin = false;
        }
      })
      .catch(() => {
        this.status = "Error";
        this.canOpenAdmin = false;
      });
  }
}
