import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <ul>
          <li>
            <a href="/">Go to home</a>
          </li>
          <li>
            <a href="/api/new-route">Go to /api/new-route</a>
          </li>
          <li>
            <a href="/api/html">Go to /api/html</a>
          </li>
          <li>
            <a href="/api/redirect">Go to /api/redirect</a>
          </li>
          <li>
            <a href="/api/redirect-ext">Go to /api/redirect-ext</a>
          </li>
          <li>
            <a href="/api/setCookie">Go to /api/setCookie</a>
          </li>
          <li>
            <a href="/api/deleteCookie">Go to /api/deleteCookie</a>
          </li>
          <li>
            <a href="/api/styled">Go to /api/styled</a>
          </li>
          <li>
            <a href="/api/ff">Go to /api/ff (should be 404!)</a>
          </li>
        </ul>
      </main>
    </>
  )
}
